(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-4',
          componentName:'NavOverflow',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:false
        });
      })({"style":{"marginHorizontal":"-6px","marginVertical":"-6px","paddingHorizontal":"6px","paddingVertical":"6px"},"activeStyle":{"marginHorizontal":"-6px","marginVertical":"-6px","paddingHorizontal":"6px","paddingVertical":"6px"},"label":"More","parentId":"n-1933619350-navId","toggleId":"19351-moreId","navBarId":"navBarId-19346","logoImageId":"logo-19345","navigation":[{"isFlyoutMenu":false,"active":false,"pageId":"2dbc3c68-54c1-4511-8f4b-14af5ec7c5f0","name":"Home","href":"\u002F","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true},{"isFlyoutMenu":false,"active":false,"pageId":"60e47323-77da-4ab1-bb82-547aa8cf25b4","name":"Contact Us","href":"\u002Fcontact-us","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":false}],"staticContent":{"hamburgerIcon":"Hamburger Site Navigation Icon","YouTube":"YouTube Social Link","cartProducts":"Products","Facebook":"Facebook Social Link","carouselAddImageHelper":"Click Here to Add Images to Slideshow!","membershipSectionTitle":"Account","membershipSignedInStatus":"Signed in as:","Xing":"Xing Social Link","membershipSignedOutStatus":"Currently not signed in","Houzz":"Houzz Social Link","morePages":"More","membershipBookings":"Bookings","Yelp":"Yelp Social Link","Google+":"Google Plus Social Link","Instagram":"Instagram Social Link","Twitter":"Twitter Social Link","translateBarHelper":"Translate: ","promoBannerLink":"Promotion Banner Link","membershipAccount":"My Account","membershipSignIn":"Sign In","navigationDropdownToggle":"Website navigation dropdown menu","cartIcon":"Shopping Cart Icon","Pinterest":"Pinterest Social Link","membershipDropdownToggle":"Website member dropdown menu","membershipCreateAccount":"Create Account","membershipOrders":"Orders","membershipSignOut":"Sign out","membershipSignOutCaps":"SIGN OUT","search_placeholder":"Search Products","LinkedIn":"LinkedIn Social Link","cartServices":"Services"},"widgetId":"fbdec8e3-e483-4850-9e5e-d0c2f6f0ccd6","section":"default","category":"accent","locale":"en-MY","renderMode":"PUBLISH"},{"widgetId":"fbdec8e3-e483-4850-9e5e-d0c2f6f0ccd6","widgetType":"HEADER","widgetPreset":"header9","section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Nav","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});